"""Publication CSV/LaTeX export and exact regression checks."""

import math
from pathlib import Path

import polars as pl

from .analysis import AnalysisResult

TABLE_FILES = {
    "timespan": "table_3_timespan",
    "standard_deviations": "table_4_standard_deviations",
    "within_country_correlations": "table_5_within_country_correlations",
    "usa_correlation_matrix": "table_6_us_correlations",
    "average_cross_country_correlations": "table_7_average_cross_country_correlations",
}


def publication_tables(results: AnalysisResult) -> dict[str, pl.DataFrame]:
    tables = dict(results.tables)
    titles = ("GDP", "Consumption", "Investment", "Government", "Net Exports", "Employment")
    span_columns = ["Country", *(f"{title} {bound}" for title in titles for bound in ("Last", "First"))]
    tables["timespan"] = tables["timespan"].rename(dict(zip(tables["timespan"].columns, span_columns, strict=True)))
    tables["standard_deviations"] = tables["standard_deviations"].rename({"country": "Country"})
    tables["within_country_correlations"] = tables["within_country_correlations"].rename({"country": "Country", "autocorrelation": "Autocorrelation"})
    usa_columns = ["Country", *(f"usa.{name}cor" for name in ("gdp", "con", "inv", "gov", "net", "emp", "sol"))]
    tables["usa_correlation_matrix"] = tables["usa_correlation_matrix"].rename(dict(zip(tables["usa_correlation_matrix"].columns, usa_columns, strict=True)))
    return tables


def csv_cell(value: object) -> str:
    # R write.csv quotes strings, leaves NA blank, and uses 15 significant digits.
    if value is None:
        return ""
    if isinstance(value, str):
        return '"' + value.replace('"', '""') + '"'
    if isinstance(value, float):
        if math.isnan(value):
            return ""
        return "0" if value == 0 else format(value, ".15g")
    return str(value)


def csv_text(table: pl.DataFrame) -> str:
    return "\n".join(
        [",".join(csv_cell(column) for column in table.columns)]
        + [",".join(csv_cell(value) for value in row) for row in table.iter_rows()]
    ) + "\n"


def latex_cell(value: object) -> str:
    if value is None:
        return ""
    text = str(value).strip()
    try:
        number = float(text)
    except ValueError:
        text = text.replace("-Q", ":")
        replacements = {"\\": r"\textbackslash{}", **{char: "\\" + char for char in "#$%&_{}"}}
        return "".join(replacements.get(char, char) for char in text)
    if not math.isfinite(number):
        return ""
    rounded = round(number, 3)
    return "0" if rounded == 0 else f"{rounded:.3f}".rstrip("0").rstrip(".")


def latex_text(table: pl.DataFrame, name: str) -> str:
    if name == "timespan":
        align = "l *{12}{c}"
    elif name == "standard_deviations":
        align = "l *{7}{S[table-format=1.3]}"
    else:
        align = f"l *{{{table.width - 1}}}{{S[table-format=-1.3]}}"
    headers = [
        latex_cell(column) if i == 0 or name == "timespan" else r"\multicolumn{1}{c}{" + latex_cell(column) + "}"
        for i, column in enumerate(table.columns)
    ]
    return "\n".join([
        "% Generated by bkk-business-cycle. Do not edit by hand.",
        r"\begin{tabular}{" + align + "}", r"\toprule", " & ".join(headers) + r" \\", r"\midrule",
        *(" & ".join(latex_cell(value) for value in row) + r" \\" for row in table.iter_rows()),
        r"\bottomrule", r"\end{tabular}", "",
    ])


def export_tables(results: AnalysisResult, output_dir: Path) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    for name, table in publication_tables(results).items():
        stem = output_dir / TABLE_FILES[name]
        stem.with_suffix(".csv").write_text(csv_text(table))
        if name == "usa_correlation_matrix":
            table = table.filter(pl.col("Country") != "USA")
            table.columns = ["Country", "y", "c", "x", "g", "nx", "n", "z"]
        stem.with_suffix(".tex").write_text(latex_text(table, name))


def check_reference(results: AnalysisResult, reference_dir: Path) -> None:
    failures = []
    for name, table in publication_tables(results).items():
        path = reference_dir / f"{TABLE_FILES[name]}.csv"
        if csv_text(table) != path.read_text():
            failures.append(path.name)
    if failures:
        raise ValueError("Results differ from reference artifacts: " + ", ".join(failures))
