latex_escape <- function(x) {
  x <- gsub("\\\\", "\\\\textbackslash{}", x)
  x <- gsub("([#$%&_{}])", "\\\\\\1", x)
  x
}

latex_cell <- function(x) {
  if (length(x) == 0 || is.na(x) || identical(x, "")) {
    return("")
  }
  if (is.numeric(x)) {
    return(format(round(x, 3), trim = TRUE, scientific = FALSE))
  }
  text <- trimws(as.character(x))
  if (grepl("^[-+]?[0-9]*\\.?[0-9]+([eE][-+]?[0-9]+)?$", text)) {
    return(format(round(as.numeric(text), 3), trim = TRUE, scientific = FALSE))
  }
  latex_escape(gsub("-Q", ":", text, fixed = TRUE))
}

latex_row <- function(values) {
  paste(vapply(values, latex_cell, character(1)), collapse = " & ")
}

latex_header <- function(values, numeric_columns = seq_along(values)[-1]) {
  cells <- vapply(seq_along(values), function(i) {
    value <- latex_cell(values[[i]])
    if (i %in% numeric_columns) {
      paste0("\\multicolumn{1}{c}{", value, "}")
    } else {
      value
    }
  }, character(1))
  paste(cells, collapse = " & ")
}

write_latex_tabular <- function(data, path, align = NULL, header = NULL) {
  if (is.null(align)) {
    align <- paste0("l", paste(rep("c", ncol(data) - 1), collapse = ""))
  }

  header_row <- if (is.null(header)) {
    latex_header(names(data), numeric_columns = integer(0))
  } else {
    header
  }

  rows <- apply(data, 1, latex_row)
  table_body <- c(
    paste0("\\begin{tabular}{", align, "}"),
    "\\toprule",
    paste0(header_row, " \\\\"),
    "\\midrule",
    paste0(rows, " \\\\"),
    "\\bottomrule",
    "\\end{tabular}"
  )

  writeLines(
    c(
      "% Generated by scripts/export_results.R. Do not edit by hand.",
      table_body
    ),
    path
  )
}
