#import "../template.typ": *

= Introduction
<introduction>
The 1982 ground-breaking paper "Time to Build and Aggregate Fluctuations" from Finn Kydland and Edward Prescott was responsible, according to #cite(<Rebelo:2005aa>, form: "prose");, for introducing three great ideas in macroeconomics: (i) dynamic general equilibrium models constitute a useful tool to study business cycles, (ii) business cycle models can be consistent with the empirical regularities of long-run growth and (iii) the comparison of model properties and stylized facts can be done in a much more quantitative fashion by calibrating these models with microeconomic data and long-run properties of the economy and then generating artificial data to be compared with actual data.

David Backus, Patrick Kehoe and Finn Kydland have applied these ideas in "International Business Cycles: theory and evidence" (1993)#footnote[This paper was later published in the book "Frontiers of Business Cycle Research" edited by Thomas F. Cooley (#cite(<Cooley:1995aa>, form: "prose");).];, henceforth BKK or BKK (1993), to analyze international comovements among countries. They have expanded #cite(<Kydland:1982aa>, form: "prose");'s RBC model to include a second country, calibrated and simulated the model and then compared the result of the simulations with the regularities actual economies experienced in the second half of last century. Among several differences between theory and data, one stood out for its robustness: the data displayed a much too high cross-country correlation of output and a much too low cross-country correlation of consumption when compared to the model's predictions. Due to its insensitivity to calibration and even to radical changes in the model structure, this difference grew to be know as the quantity anomaly. Further research on international business cycle have taken these empirical findings for granted and many of the following DSGE models were built to accommodate them.

Given the relevance of BKK findings to the subsequent research in the field of international business cycles, we reassess BKK's empirical results in the present paper using 23 years of extra data. In @sec:themodel we shortly introduce the baseline model BKK have used to generate the simulations of international business cycles and compare it with its closed-economy version. We also point out the modifications BKK made to the baseline model, which, despite their success in correcting other discrepancies between model and data, were not able to solve the quantity anomaly. We then analyze in @sec:thedata the specificities of our data and how it compares to BKK's. We also comment on the implications of the Hodrick-Prescott filter, which was the method used by BKK to filter the data. In @sec:theresults, we redo exactly the same calculations BKK have done using our wider time frame and compare the results. We then use an alternative approach to measure international comovements and compare our results not only to BKK's but also to #cite(<Ambler:2004aa>, form: "prose");'s, who have completed a similar analysis. We conclude that the quantity anomaly persists and end the paper by indicating how more recent models have dealt with international business cycles and sought to accommodated the quantity anomaly.

Before starting the next section, we would like to emphasize that this paper aims to be reproducible.#footnote[The #emph[ultimate] standard for judging scientific research is replication. Yet, it's not always possible to fully replicate an experiment. In our case, for example, one would have to independently gather data on all analyzed economic variables for each country once again. Such a task is virtually impossible. The concept of reproducible research tries to bridge the gap between mere publication of results and full replication of research. This is accomplished by making available, along with the results, the data set and the computer code used to analyze it. In this sense, reproducibility is a #emph[minimum] standard to judge scientific claims. See #cite(<Peng:2011aa>, form: "prose");.] The data and the R code used to analyze it are all available online.#footnote[The code with instructions and all the data used in this paper can be downloaded at #link("https://denismaciel.github.io/BKK-International-Business-Cycle/");.]
