#import "../template.typ": *

= The Model <sec:themodel>
Dynamic general equilibrium models have been successful in explaining many features of business cycles (#cite(<Prescott:1986aa>, form: "prose");). #cite(<Kydland:1982aa>, form: "prose");'s famous closed-economy model, in which a single aggregate productivity shock generates the business cycles, has been able to account for the magnitude of variations in output, consumption and investment and for the correlations of consumption and investment with output that actual economies experience. Their model generates most of the regularities that can be seen in the data: consumption and investment that are positively correlated with output (i.e. procyclical) and volatilities of investment and consumption that are respectively higher and lower than output volatility.

== BKK's Expanded Model
<bkks-expanded-model>
#cite(<Backus:1992aa>, form: "prose") take the model a step further and expand it to include two countries with imperfectly correlated technology shocks. By doing so, they attempt to apply the Real Business Cycle (RBC) framework to explain international business cycles. The expanded model need not only to maintain the good results of its closed-economy predecessor by explaining variations and comovements within a country, but it should also be able to reproduce the cross-country comovements of variables that characterizes the international business cycle.

To generate the simulations, BKK (1993) use a more simple version of BKK's (1992) expanded model. It consists of two countries that produce one unique good and have the same preferences and production technology. The single source of uncertainty in the model are country-specific technology shocks to total factor productivity, which are also the drivers of the business cycles. Households maximize over time a utility function that depends on consumption and leisure and provide the labour, which, together with capital, constitutes the input for the production function.

@tab:modelresult shows the results obtained by simulating four different models. The first row refers to #cite(<Kydland:1982aa>, form: "prose");'s closed economy. The second row refers to the simplest expanded model of BKK (1993) with complete markets and no costs of transportation. The last two rows refer to modifications to the expanded model. In the third row, the model is simulated with transportation costs and, in the fourth, the possibility of trade between the two countries is excluded.

The ability to borrow in international markets have a significant influence on the fluctuations of consumption and investment, since both variables are no longer constrained by the country's production. In comparison to the closed-economy model, consumption and investment become less correlated to output. Investment volatility also increases because the ability to freely move resources across borders leads the country with the more favorable technology shock to receive a greater amount of capital than it would have received in a closed setup.

#model-table() <tab:modelresult>

== The Quantity Anomaly
<the-quantity-anomaly>
The two-country RBC model in its simplest form (@tab:modelresult: Benchmark), i.e. with free movements of goods and financial assets and absence of transportation costs, differs in various aspects from the data. In this model, investment and net exports are too volatile, consumption is too smooth and outputs of the two countries are negatively correlated. In this sense, the closed-economy model fares much better than its international, two-country version in mimicking the data. Most of these discrepancies between theory and data disappear, however, when either the parameter values or the structure of the model are changed. For example, the volatility of net exports and of investment, which are respectively seven and three times higher in the model, decrease to the levels observed in the data as quadratic transport costs are incorporated into the model (@tab:modelresult: Transport Cost).

One specific discrepancy, however, proved to be highly robust. The ranking of cross-country correlations that results from the model $\( rho_(c \, c^(\*)) > rho_(y \, y^(\*)) \)$ is the exact opposite to the one found in the data ($rho_(y \, y^(\*)) > rho_(c \, c^(\*))$). The theoretical economy originates correlations of consumption across countries that are larger than the cross-country output correlations. Yet, in the data, output has a higher correlation than consumption across countries. BKK named this discrepancy the quantity anomaly#footnote[BKK (1993) identified also a second anomaly: the standard deviation of terms of trade is larger in the data than it is in the model. Nevertheless, we will focus only on the quantity anomaly in this paper.] because of its insensitivity to changes not only in the parameters of the model but also in the model's structure.

== Robustness of the Quantity Anomaly
<robustness-of-the-quantity-anomaly>
Correlation between outputs in the model is negative (-0.21). Conversely, output correlation between the USA and other ten countries are all positive in BKK data set; the highest correlation being with Canada (0.76) and the lowest with Austria (0.38). The model presents a negative correlation of output of the two countries because a positive technology shock in one country increases the marginal productivity of both labor and capital in it. The higher returns create the incentive to move the factors of production from the other country to the country experiencing the most favorable technology shock. Accordingly, output increases in one country at the expenses of the other.

On the other hand, consumption between the two countries will be perfectly correlated in the model economy, if markets are complete -- i.e. if agents can share risks across countries -- and preferences are additively separable between consumption and leisure (#cite(<Scheinkman:1984aa>, form: "prose");). In BKK's benchmark model, although markets are complete, preferences are nonseparable. For that reason, the correlation of consumption of the two countries in the model is 0.88 instead of one. Although not perfectly correlated, consumption displays a much too high cross-country correlation when compared to BKK's data (0.51 between US and Europe).

To address these two issues (high correlation of consumption and low correlation of output), BKK completely ban risk sharing between countries from the model (@tab:modelresult: Autarky). There is no trade of goods or securities and the only link between the two countries in the resulting autarky is the positive correlation between technology shocks. In this extreme experiment, cross-country correlation drops to 0.56 but output correlation stays much less positively correlated (0.08) than it is in the data (0.70 between US and Europe). The high correlation between consumption levels even under complete ban of risk sharing, BKK speculate, might be attributed to the permanent income hypothesis: with a positive technology shock affecting one country, the agents of the other are aware that the shock will spill over and so increase consumption in the present and delay investment into the future.

Cross-country correlations of consumption and output are deeply related in the model. One can increase the correlation of output between the two countries by making productivity shocks more highly correlated. This, however, comes at the cost of decreasing the consumption correlation. By choosing different values for the shock correlation, the model can mimic either the correlation of consumption or the correlation of output in the data, but not both at the same time. In this sense, the quantity anomaly refers not to the size of output and consumption correlation individually. Instead, the relative size of output and consumption correlations constitutes the anomalous behavior of the model.
